version: '3.3'
services:
  db:
    image: mysql:8.0.32
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'area'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 50s
      timeout: 1m
      retries: 10
    volumes:
      - ./backend/mysql_data/:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      - PMA_HOST=db
    depends_on:
      db:
        condition: service_healthy

  backend:
    build : backend/
    restart: always
    image: area-api-back
    container_name: area-api-back
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
    expose:
      - '8080'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD","wget",'http://localhost:8080/about.json']
      interval: 15s
      timeout: 1m
      retries: 15

  front-mobile:
    build: mobile/
    image: area-front-mobile
    container_name: area-mobile
    volumes:
      - area-front:/app/

  frontend-web:
    build: web/
    restart: always
    image: area-front-web
    container_name: area-web
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      backend:
        condition: service_healthy
      front-mobile:
        condition: service_completed_successfully
    volumes:
      - area-front:/app/public/apk/

volumes:
  area-front:
